apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metacat.fullname" . }}
  labels:
    {{- include "metacat.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metacat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metacat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metacat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: metacat-web
            - containerPort: 8009
              name: apache-connect
            - containerPort: 5701
              name: hazelcast
            - containerPort: 5005
              name: metacat-debug
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env: 
            # TODO - MB:
            # ADMINPASS SHOULD BE IN SECRETS! Better still, how can we omit this step altogether? (Used only by 
            # docker-entrypoint.sh to curl-login to metacat admin interface.)
            - name: ADMIN
              value: admin@localhost
            - name: ADMINPASS
              value: admin
          volumeMounts:
            - mountPath: /etc/metacat/metacat-site.properties.readonly
              subPath: metacat-site.properties
              name: {{ .Release.Name }}-config-volume
          livenessProbe:
            httpGet:
              path: /
              port: metacat-web
          readinessProbe:
            httpGet:
              path: /
              port: metacat-web
      volumes:
        - name: {{ .Release.Name }}-config-volume
          configMap:
            name: {{ .Release.Name }}-configfiles
            defaultMode: 0644
