{{- $ingresstype:=(include "metacat.ingress.type" .) -}}
{{- if not (eq $ingresstype "disabled") -}}
{{- $isNginx := eq $ingresstype "nginx" -}}
{{- $isTraefik := eq $ingresstype "traefik" -}}
{{/* ==== Validate .Values.ingress input, since syntax differs bwtween nginx and Traefik ========= */}}
{{- if .Values.ingress.rewriteRules }}
{{- if kindIs "string" .Values.ingress.rewriteRules }}
  {{- if not $isNginx }}
    {{- fail "Values.ingress.rewriteRules must be **SINGLE STRING** of formatted nginx markup, not a yaml list" -}}
  {{- end }}
{{- else if (ne (len .Values.ingress.rules) 0) }}
  {{- if not $isTraefik }}
    {{- fail "Values.ingress.rewriteRules must be a yaml list of Middleware values, not a string" -}}
  {{- end }}
{{- end }}
{{- end }}
{{/* ==== End validation ========================================================================= */}}
{{- $fullName := include "metacat.fullname" . -}}
{{- $serverName := ( include "metacat.server.name" . ) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "metacat.labels" . | nindent 4 }}
  {{- $mutualAuth := index .Values.metacat "dataone.certificate.fromHttpHeader.enabled" -}}
  {{- $siteMapEnabled := index .Values.metacat "sitemap.enabled" }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end -}}
    {{- if $isTraefik }}
      {{- if $mutualAuth }}
        {{- include "dataone.traefik.mtls.annotations" . | nindent 4 }}
      {{- end }}
    {{- end }}
    {{- if $isNginx }}
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1m
    nginx.ingress.kubernetes.io/client-max-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
    {{- if .Values.ingress.configurationSnippet }}
      {{- .Values.ingress.configurationSnippet | nindent 6 }}
    {{- end }}
    {{- if .Values.ingress.corsEnabled }}
      # Metacat Cors Setup

      set $cors 'true';

      if ($request_method = 'OPTIONS') {
        set $cors ${cors}options;
      }

      if ($cors = "true") {
        more_set_headers 'Access-Control-Allow-Origin: $http_origin';
        more_set_headers 'Access-Control-Allow-Credentials: true';
        more_set_headers 'Access-Control-Allow-Methods: POST, PUT, GET, OPTIONS';
        more_set_headers 'Access-Control-Allow-Headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';

        more_set_headers 'Access-Control-Max-Age: 1728000';
      }

      if ($cors = "trueoptions") {
        more_set_headers 'Access-Control-Allow-Origin: $http_origin';
        more_set_headers 'Access-Control-Allow-Credentials: true';
        more_set_headers 'Access-Control-Allow-Methods: POST, PUT, GET, OPTIONS';
        more_set_headers 'Access-Control-Allow-Headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';

        more_set_headers 'Access-Control-Max-Age: 1728000';
        more_set_headers 'Content-Type: text/plain charset=UTF-8';
        more_set_headers 'Content-Length: 0';
        return 204;
      }
    {{- end }}
    {{- if $siteMapEnabled }}
      rewrite ^/(sitemap.+) /{{- index .Values.metacat "application.context" -}}
      /sitemaps/$1 redirect;
    {{- end }}
      rewrite ^/robots.txt /{{- index .Values.metacat "application.context" -}}
      /robots.txt redirect;
    {{- if .Values.ingress.rewriteRules }}
      {{- .Values.ingress.rewriteRules | nindent 6 }}
    {{- end }}
    {{- if $mutualAuth -}}
      {{- include "dataone.nginx.mtls.snippets" . | nindent 6 }}
      {{- include "dataone.nginx.mtls.annotations" . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.ingress.defaultBackend.enabled }}
  defaultBackend:
  {{- omit .Values.ingress.defaultBackend "enabled" | toYaml | nindent 4 }}
  {{- end }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
    {{- if eq (len .hosts) 0 }}
        - {{ $serverName }}
    {{- else }}
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
    {{- end }}
      secretName: {{ required ".Values.ingress.tls.secretName REQUIRED" .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- if and (.Values.ingress.rules) (ne (len .Values.ingress.rules) 0) }}
    {{- .Values.ingress.rules | toYaml | nindent 4 }}
  {{- else }}
    - host: {{ $serverName }}
      http:
        paths:
          - path: /{{ index .Values.metacat "application.context" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-hl
                port:
                  number: 8080
          {{- $webroot := regexReplaceAll "/$" .Values.global.metacatUiWebRoot "" }}
          {{- if .Values.global.includeMetacatUi }}
          - path: {{ $webroot }}/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-metacatui
                port:
                  number: 80
          {{- else }}
            {{- if .Values.global.metacatUiIngressBackend.enabled }}
          - path: {{ $webroot }}/
            pathType: Prefix
            backend:
              {{- omit .Values.global.metacatUiIngressBackend "enabled" | toYaml | nindent 14 }}
            {{- end }}
          {{- end }}
{{- end }}
{{- end }}
