{{- if eq (include "metacat.ingress.type" .) "traefik"}}
{{- $siteMapEnabled := index .Values.metacat "sitemap.enabled" }}
{{- $mtlsEnabled := index .Values.metacat "dataone.certificate.fromHttpHeader.enabled" -}}
##
## Only one middleware can be added to the ingress annotations. This middleware "chain" definition
## chains together all the other Traefik Middlewares, so only this one needs to be referenced
## in the ingress annotations.
##
## * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
## IMPORTANT: ADD THE NAMES OF ANY NEW MIDDLEWARES TO THIS TEMPLATE, OR THEY WON'T BE LOADED!
## * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
##
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-middlewares
  namespace: {{ .Release.Namespace }}
spec:
  chain:
    middlewares:
    {{- if $siteMapEnabled }}
      - name: {{ .Release.Name }}-sitemap-redirect
    {{- end }}
      - name: {{ .Release.Name }}-robots-redirect
    {{- range .Values.ingress.rewriteRules }}
      - name: {{ $.Release.Name }}-{{ .name }}
    {{- end }}
    {{- if $mtlsEnabled }}
      - name: {{ .Release.Name }}-passcert
      - name: {{ .Release.Name }}-customheaders
    {{- end }}
{{- end }}
