{{- if eq (include "metacat.ingress.type" .) "traefik"}}
{{- if index .Values.metacat "dataone.certificate.fromHttpHeader.enabled" -}}
##
## This file contains the Traefik TLSOption and Middleware definitions required in order to make
## mutual TLS work.
##
## IMPORTANT: ADD THE NAMES OF ANY NEW MIDDLEWARES TO helm/templates/middleware-chain.yaml, OR THEY
## WON'T BE LOADED!
##
---

##
## Traefik TLSOption for verifying mutual TLS (mTLS) client cert
##
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: {{ .Release.Name }}-mtls-policy
  namespace: {{ .Release.Namespace }}
spec:
  clientAuth:
    clientAuthType: VerifyClientCertIfGiven
    secretNames:
      - {{ .Values.ingress.d1CaCertSecretName }}

---

## This Middleware passes the client certificate to the upstream Metacat service. It's the Traefik
## equivalent of the Nginx snippet:
## nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
##
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-passcert
  namespace: {{ .Release.Namespace }}
spec:
  passTLSClientCert:
    pem: true
    info:
      subject:
        country: true
        province: true
        locality: true
        organization: true
        organizationalUnit: true
        commonName: true
        serialNumber: true
        domainComponent: true
---
## This Middleware adds the X-Proxy-Key header to the request, and prevents clients spoofing the
## Ssl-Client-Verify or Ssl-Client-Subject-Dn headers. It's the Traefik equivalent of Nginx snippet:
## nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
##
{{- $apiVer := "v1" -}}
{{- $xProxyKeyKey := "METACAT_DATAONE_CERT_FROM_HTTP_HEADER_PROXY_KEY" -}}
{{- $secrets := (printf "%s-metacat-secrets" .Release.Name) -}}
{{- $secretData := (lookup $apiVer "Secret" .Release.Namespace $secrets).data | default dict -}}
{{- $xProxyKeyVal := ((get $secretData $xProxyKeyKey) | b64dec)
    | default (printf "SECRETS: '%s'; KEY NOT FOUND: '%s'" $secrets $xProxyKeyKey) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-customheaders
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Proxy-Key: {{ $xProxyKeyVal | quote }}
      Server: traefik
      Ssl-Client-Verify: ""          # overwrite to prevent client setting
      Ssl-Client-Subject-Dn: ""      # overwrite to prevent client setting
{{- end }}
{{- end }}
