apiVersion: v1
kind: Service
metadata:
  name: {{ include "metacat.fullname" . }}-headless-svc
  labels:
    {{- include "metacat.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  # The StatefulSet’s governing Service must be headless.
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
      {{- include "metacat.selectorLabels" . | nindent 4 }}
