## override values.yaml with values to use for running on the NCEAS dev cluster
##
## examples:
## from local helm chart:
##  helm install myrelease -n mynamespace ./helm -f ./helm/examples/values-dev-cluster-example.yaml
##
## or from pre-packaged chart:
##  helm install myrelease -n mynamespace -f ./helm/examples/values-dev-cluster-example.yaml \
##       --debug --render-subchart-notes oci://ghcr.io/nceas/charts/metacat --version <myversion#>
##
## see values.yaml for full documentation on the following parameters
##

## set once here, for both metacat and indexer:
## Omit for production - otherwise logging is too verbose
debug: &debug true

global:
  metacatExternalBaseUrl: "https://metacat-dev.test.dataone.org/"
  d1ClientCnUrl: "https://cn-sandbox.test.dataone.org/cn"
  storageClass: csi-cephfs-sc
  ephemeralVolumeStorageClass: csi-cephfs-sc-ephemeral
  ## Use your own release name instead of metacatbrooke
  passwordsSecret: &passwordSecretName metacatbrooke-metacat-secrets
  ## MetacatUI is deployed as a separate chart, to allow for a different upgrade cycle.
  ## see separate values overrides in ./values-dev-cluster-example-mcui.yaml
  ##
  includeMetacatUi: false           # don't include the MetacatUI sub-chart
  metacatUiIngressBackend:
    enabled: true                   # configure the Ingress to point to the MetacatUI service
    service:
      name: mcuibrooke-metacatui    # Use your own service name

metacat:
  auth.administrators: http://orcid.org/0000-0002-1472-913X;http://orcid.org/0000-0002-1209-5268

#  storage.hashstore.disableConversion: true

  ## DataONE Member Node (MN) Parameters
  dataone.certificate.fromHttpHeader.enabled: true
  dataone.autoRegisterMemberNode: 2025-01-23
  dataone.nodeId: "urn:node:TestBROOKELT"
  dataone.subject: "CN=urn:node:TestBROOKELT,DC=dataone,DC=org"
  dataone.nodeName: TestBROOKELT Metacat Node
  dataone.nodeDescription: |
    Dev cluster Test BROOKE LT Metacat Node. Last registered with CN on 1/23/2025
  ## FOR TESTING: NON-VERIFIED:  CN=Christopher Jones A2108,O=Google,C=US,DC=cilogon,DC=org
  dataone.contactSubject: http://orcid.org/0000-0002-1472-913X
  dataone.nodeSynchronize: true
  dataone.nodeReplicate: true
  dataone.replicationpolicy.default.numreplicas: "1"

persistence:
  size: 100Gi
  accessModes:
    - ReadWriteMany
  ## Use your own release name instead of metacatbrooke
  volumeName: cephfs-metacatbrooke-metacat

image:
  # tag: TEST
  pullPolicy: Always
  debug: *debug

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 2
    memory: 4Gi

tomcat:
  ## @param tomcat.jmxEnabled Enable JMX for Tomcat, to inspect JVM usage of CPU, memory, etc.
  ## When JMX is enabled by setting this to 'true', you can view the JMX metrics using a JMX client
  ## such as VisualVM or JConsole, connected via port-forwarding to the port set in tomcat.jmxPort
  ##
  jmxEnabled: true

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts: [] # defaults to global.metacatExternalBaseUrl
      secretName: ingress-nginx-tls-cert

database:
#  dbName: metacat  # already default
#  dBUser: metacat  # already default
  existingSecret: cnpgtest011mc-cnpg-app
  serviceName: cnpgtest011mc-cnpg-rw

dataone-indexer:
  autoscaling:
    minReplicas: 1
    targetCPUUtilizationPercentage: 80

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1.0
      memory: 4Gi

  image:
    pullPolicy: Always
    debug: *debug

  idxworker:
    jmxEnabled: true
    # this actually puts container in debug loop mode - no indexer running
    debug: false

  rabbitmq:
    auth:
      existingPasswordSecret: *passwordSecretName
    resources:
      requests:
        cpu: 1.0
        memory: 2048Mi
      limits:
        cpu: 3.0
        memory: 3072Mi

  solr:
    javaMem: "-XX:MaxRAMPercentage=75.0"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1.5
        memory: 4Gi
    extraVolumes:
      - name: solr-config
        configMap:
          ## Use your own release name instead of metacatbrooke
          name: metacatbrooke-indexer-configfiles
          defaultMode: 0777

####################################################################################################
## FOR DEBUGGING ONLY
####################################################################################################
##
## probes will kill remote debugger
#
#livenessProbe:
#  enabled: false
#readinessProbe:
#  enabled: false
#
#service:
#  enabled: true
#  type: LoadBalancer
#  clusterIP: ""
#  ports:
#    - name: debug-port
#      port: 5005
#      targetPort: tc-remote-debug
#
#container:
#  ports:
#    - containerPort: 5005
#      name: tc-remote-debug
