## override values.yaml with values to use for running on the NCEAS dev cluster
##
## examples:
## from local helm chart:
##  helm install myrelease -n mynamespace ./helm -f ./helm/examples/values-dev-cluster-example.yaml
##
## or from pre-packaged chart:
##  helm install myrelease -n mynamespace oci://ghcr.io/nceas/charts/metacat --version 1.1.1 \
##       -f ./helm/examples/values-dev-cluster-example.yaml \
##       --debug --render-subchart-notes
##
## see values.yaml for full documentation on the following parameters
##

# set once here, for both metacat and indexer:
debug: &debug true

global:
  metacatUiThemeName: "default"
  metacatUiWebRoot: "/"
  metacatExternalBaseUrl: "https://metacat-dev.test.dataone.org/"
  d1ClientCnUrl: "https://cn-stage.test.dataone.org/cn"
  storageClass: &storageClassName csi-cephfs-sc
  ephemeralVolumeStorageClass: csi-cephfs-sc-ephemeral
  passwordsSecret: &passwordSecretName metacatbrooke-metacat-secrets


## example for a custom theme (also need to set global.metacatUiThemeName: "cerp", above)
##
#metacatui:
#  customTheme:
#    enabled: true
#    claimName: metacatbrooke-metacatui-customtheme
#    subPath: metacatui-themes/src/cerp/js/themes/cerp
#  appConfig:
#    enabled: false
    ## disabled because SFWMD uses cerp theme, overlaid with
    ## SFWMD config.js at /config/config.js (created as configMap)

metacat:
  server.name: metacat-dev.test.dataone.org
  ## Matthew Brooke; Jing Tao; Matt Jones; Jeanette Clark
  auth.administrators: http://orcid.org/0000-0002-1472-913X;http://orcid.org/0000-0002-1209-5268;https://orcid.org/0000-0003-0077-4738;http://orcid.org/0000-0003-4703-1974

  cn.server.publiccert.filename: /var/metacat/pubcerts/DataONETestIntCA.pem

#  storage.hashstore.disableConversion: true

  ## DataONE Member Node (MN) Parameters
  dataone.certificate.fromHttpHeader.enabled: true
  dataone.autoRegisterMemberNode: 2024-01-25
  dataone.nodeId: "urn:node:TestBROOKELT"
  dataone.subject: "CN=urn:node:TestBROOKELT,DC=dataone,DC=org"
  dataone.nodeName: Test BROOKE LT Metacat Node
  dataone.nodeDescription: Dev cluster Test BROOKE LT Metacat Node
  dataone.contactSubject: http://orcid.org/0000-0002-1472-913X
  dataone.nodeSynchronize: true
  dataone.nodeReplicate: true
  dataone.replicationpolicy.default.numreplicas: "1"

persistence:
  storageClass: *storageClassName
  size: 100Gi
  accessModes:
    - ReadWriteMany
  volumeName: cephfs-metacatbrooke-metacat

image:
  # tag: TEST
  pullPolicy: Always
  debug: *debug

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts: [] # defaults to metacat.server.name
      secretName: ingress-nginx-tls-cert

postgresql:
  ## @param postgresqlDataDir PostgreSQL data dir folder
  ##
  postgresqlDataDir: /bitnami/postgresql/14/main

  primary:
    extendedConfiguration: |
      max_connections = 250
      max_wal_size=16384
      min_wal_size=4096
      shared_buffers = 1280MB

    persistence:
      size: 10Gi
      selector:
        matchLabels:
          metacatVolumeName: cephfs-metacatbrooke-metacat-postgresdata

  auth:
    existingSecret: *passwordSecretName

dataone-indexer:
  # increase minReplicas from default 3
  autoscaling:
    minReplicas: 3
    targetCPUUtilizationPercentage: 80

  image:
    pullPolicy: Always
    debug: *debug

  topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: d1index

  idxworker:
    # this actually puts container in debug loop mode - no indexer running
    debug: false

  rabbitmq:
    auth:
      existingPasswordSecret: *passwordSecretName

  solr:
    extraVolumes:
      - name: solr-config
        configMap:
          name: metacatbrooke-indexer-configfiles
          defaultMode: 0777

####################################################################################################
## FOR DEBUGGING ONLY
####################################################################################################
##
## probes will kill remote debugger

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

#service:
#  enabled: true
#  type: LoadBalancer
#  clusterIP: ""
#  ports:
#    - name: debug-port
#      port: 5005
#      targetPort: tc-remote-debug
#
#container:
#  ports:
#    - containerPort: 5005
#      name: tc-remote-debug
