apiVersion: v1
kind: Service
metadata:
  name: metacat-service
  labels:
    app: metacat
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: metacat-web
    - port: 8009
      name: apache-connect
    - port: 5701
      name: hazelcast
    - port: 5005
      name: metacat-debug
  selector:
    app: metacat
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metacat-env
  labels:
    app: metacat
data:
  ADMIN: admin@localhost
  ADMINPASS: admin
  HOST: metacat.example.com
  METACAT_APP_CONTEXT: metacat
  METACAT_VERSION: 2.18.0
  PORT: "8080"
  POSTGRES_HOST: 192.168.0.25  # needs an IP address - no dns?
  POSTGRES_DB: metacat
  POSTGRES_USER: metacat
  POSTGRES_PASSWORD: metacat
  SOLR_HOST: 192.168.0.25  # needs an IP address - no dns?
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metacat-deployment
  labels:
    app: metacat
spec:
  replicas: 1 # default
  selector:
    matchLabels:
      app: metacat
  template:
    metadata:
      labels:
        app: metacat
    spec:
      containers:
        - name: metacat
          image: metacat:2.18.0
          env:
            - name: ADMIN
              valueFrom:
                configMapKeyRef:
                  key: ADMIN
                  name: metacat-env
            - name: ADMINPASS
              valueFrom:
                configMapKeyRef:
                  key: ADMINPASS
                  name: metacat-env
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: metacat-env
            - name: METACAT_APP_CONTEXT
              valueFrom:
                configMapKeyRef:
                  key: METACAT_APP_CONTEXT
                  name: metacat-env
            - name: METACAT_VERSION
              valueFrom:
                configMapKeyRef:
                  key: METACAT_VERSION
                  name: metacat-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: metacat-env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: metacat-env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: metacat-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: metacat-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: metacat-env
            - name: SOLR_HOST
              valueFrom:
                configMapKeyRef:
                  key: SOLR_HOST
                  name: metacat-env
            # valueFrom:
            #   secretKeyRef:
            #     name: mysql-pass
            #     key: password
          ports:
            - name: mc-web-cp
              containerPort: 8080
            - name: mc-debug-cp 
              containerPort: 5005
            - name: mc-apache-conn
              containerPort: 8009
            - name: mc-hzlcst
              containerPort: 5701
          # readinessProbe:
          #   httpGet:
          #     path: /metacat/admin
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          #   failureThreshold: 1
      #     volumeMounts:
      #     - name: metacat-persistent-storage
      #       mountPath: /var/metacat_test_mount
      # volumes:
      # - name: metacat-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mc-pv-claim