# Creates a persistent volume for use by metacat
#
# This should be done only one time, separately from the helm install/upgrade cycle
#
apiVersion: v1
kind: PersistentVolume
metadata:
  # See https://github.com/DataONEorg/k8s-cluster/blob/main/storage/storage.md#dataone-volume-naming-conventions
  # cephs-{release}-{function}-{instance}, where {release} usually = {namespace}
  #
  ## Use your own release name
  name: &pv-name cephfs-releasename-metacat-varmetacat
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # Use your own secret name
      name: csi-cephfs-releasename-secret
      # Use your own namespace where above secret is created
      namespace: ceph-csi-cephfs
    volumeAttributes:
      # Use your own clusterID, fsName, rootPath etc. here
      clusterID: 8aa4d4a0-a209-11ea-baf5-ffc787bfc812
      fsName: cephfs
      rootPath: /volumes/k8ssubvolgroup/k8ssubvol/58cda964-ce10-4ff9-8242-983da0fd0da3/repos/name/metacat
      staticVolume: "true"
    volumeHandle: *pv-name
  persistentVolumeReclaimPolicy: Retain
  ## Use your own storage class
  storageClassName: csi-cephfs-sc
  volumeMode: Filesystem
