# For development use:
# Create a persistent volume using the filesystem on the local machine.
# Edit the "spec.hostpath.path" below, and then create by running the command:
#     kubectl apply -f pv-hostpath.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: metacat-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    # ReadWriteOnce:
    # the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still
    # can allow multiple pods to access the volume when the pods are running on the same node.
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # path: /path/on/local/dev/filesystem
    path: /var/metacat-pv
    # Note: if using Rancher Desktop on a Mac, k8s runs inside a virtual machine, so the directory
    # /var/metacat-pv used by the persistent volume mount is not the same as the /var/metacat-pv on
    # the mac's hard drive. However, the directories in the user's home directory ARE share with
    # the VM, so you can target a directory there if you want to access the contents. You can
    # gain access to the vm filesystem using the command:
    # LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" \
    #     "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" \
    #     shell 0
