# Creates a persistent volume claim for use by postgresql
#
# This should be done only one time, separately from the helm install/upgrade cycle
#
# NOTE: ensure that a PersistentVolume has already been created before creating
#       the PersistentVolumeClaim!
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  ## Use your own release name
  name: releasename-metacat-postgresql-0
  ## Use your own namespace
  namespace: mynamespace
spec:
  accessModes:
    - ReadWriteOnce
  ## Use your own release name. Note must match the name of the PersistentVolume
  volumeName: cephfs-releasename-metacat-postgresdata
  resources:
    requests:
      storage: 1000Gi
  ## Use your own storage class
  storageClassName: csi-cephfs-sc
