######################################################################################
#     D O   N O T   C H E C K   C R E D E N T I A L S   I N T O   G I T H U B ! ! !
######################################################################################
#
# Edit this file to add your passwords, then install them in your cluster by one of the
# following methods. Assuming your release name is "my-release": (NOTE THE RELEASE NAME MUST
# MATCH THE ONE YOU USE WITH HELM!)
#
# 1. Define the release name on the command line:
#     $  RELEASE_NAME=my-release  envsubst < secrets.yaml | kubectl apply -n <mynamespace> -f -
#
#     # if this results in "command not found: envsubst", you can install envsubst (e.g. on Mac OS:
#        $  brew install gettext && brew link --force gettext
#
# 2. Alternatively, you can simply replace "${RELEASE_NAME}" in the file below (be sure to retain
#    the "-secrets" part), and do:     $  kubectl apply -n <mynamespace> -f secrets.yaml)
#
apiVersion: v1
kind: Secret
metadata:
  name: ${RELEASE_NAME}-secrets
type: Opaque
stringData:    # # # EDIT THESE VALUES # do not check into GitHub!
  # METACAT_AUTH_ADMINISTRATORS is a single admin username or LDAP-style Distinguished Name used
  # to log into the metacat admin pages. It is NOT a list of users (despite its name), and must
  # not contain any colons (:)
  METACAT_AUTH_ADMINISTRATORS: your-value-here    # account will be created if not already existing
  METACAT_ADMINISTRATOR_PASSWORD: your-value-here # account will be created if not already existing
  POSTGRES_PASSWORD: your-value-here              # for existing postgres account
  POSTGRES_USER: your-value-here                  # for existing postgres account
  METACAT_GUID_DOI_USERNAME: your-value-here      # can be ignored if not using DOI
  METACAT_GUID_DOI_PASSWORD: your-value-here      # can be ignored if not using DOI
  METACAT_REPLICATION_PRIVATE_KEY_PASSWORD: ""    # can be ignored if not using CN -> CN replication
data: {}
