## Create a basic-auth secret for the PostgreSQL cluster
## (Required for clusters created by CloudNative-PG operator:
## https://github.com/cloudnative-pg/cloudnative-pg)
##
######################################################################################
#     D O   N O T   C H E C K   C R E D E N T I A L S   I N T O   G I T H U B ! ! !
######################################################################################
#
# Edit this file to add your username and password, then install it in your cluster by one of the
# following methods. Assuming your release name is "myrelease": (NOTE THE RELEASE NAME MUST
# MATCH THE ONE YOU USE WITH HELM!)
#
# 1. Define the release name on the command line:
#      $ RELEASE_NAME=myrelease PASSWORD=YOUR-PASSWORD-HERE \
#            envsubst < cloudnative_pg_secret.yaml | kubectl apply -n <mynamespace> -f -
#
# 2. Alternatively, you can simply replace "${RELEASE_NAME}" (be sure to retain the "-metacat-cnpg"
#    part) and "$PASSWORD" in the file below, and do:
#      $ kubectl apply -n <mynamespace> -f cloudnative_pg_secret.yaml
#
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  ##############################################
  ##  EDIT THIS TO SUBSTITUTE YOUR RELEASE NAME
  ##############################################
  name: ${RELEASE_NAME}-metacat-cnpg

## @param stringData write-only, non-binary secret data (eg credentials) in string form.
##
## # # #    NEVER CHECK SECRETS INTO GITHUB!   # # #
##
stringData:
  username: "metacat"
  password: "$PASSWORD"  # replace with your password
