######################################################################################
#     D O   N O T   C H E C K   P A S S W O R D S   I N T O   G I T H U B ! ! !
######################################################################################
#
# Edit this file to add your passwords, then install them in your cluster by
# running the command:    kubectl apply -n <mynamespace> -f secrets.yaml
#
apiVersion: apps/v1
kind: Secret
metadata:
  name: metacat-secrets
type: Opaque
stringData:    # # # EDIT THESE VALUES # do not check into GitHub!
  metacat.administratorPassword: your-value-here
#  metacat.administratorUsername: your-value-here
#  metacat.databasePassword: your-value-here
#  metacat.databaseUsername: your-value-here
#  metacat.guidDoiUsername: your-value-here
#  metacat.guidDoiPassword: your-value-here
data: {}
