######################################################################################
#     D O   N O T   C H E C K   C R E D E N T I A L S   I N T O   G I T H U B ! ! !
######################################################################################
#
# Edit this file to add your credentials, then install them in your cluster by
# running the command:    kubectl apply -n <mynamespace> -f secrets.yaml
#
apiVersion: v1
kind: Secret
metadata:
  name: metacat-secrets
type: Opaque
stringData:    # # # EDIT THESE VALUES # do not check into GitHub!
  # METACAT_AUTH_ADMINISTRATORS is a single admin username or LDAP-style Distinguished Name used
  # to log into the metacat admin pages. It is NOT a list of users (despite its name), and must
  # not contain any colons (:)
  METACAT_AUTH_ADMINISTRATORS: your-value-here
  METACAT_ADMINISTRATOR_PASSWORD: your-value-here
  POSTGRES_PASSWORD: your-value-here
  POSTGRES_USER: your-value-here
  METACAT_GUID_DOI_USERNAME: your-value-here
  METACAT_GUID_DOI_PASSWORD: your-value-here
  METACAT_REPLICATION_PRIVATE_KEY_PASSWORD: ""
data: {}
