apiVersion: v2
name: metacat
description: |
  Helm chart for Kubernetes Deployment of MetaCat 
  (https://github.com/NCEAS/metacat)

# OCI Annotations - see https://github.com/helm/helm/pull/11204
sources:
  - https://github.com/NCEAS/metacat

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "2.1.2"
icon: https://github.com/NCEAS/metacat/blob/develop/docs/dev/images/metacat-logo.png

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# NOTE that the chart will pull the docker image whose tag matches this value, if 'image.tag' is
# not set in values.yaml
appVersion: "3.2.2"

# Chart dependencies - also see https://github.com/bitnami/charts/tree/main/bitnami
dependencies:
  - name: metacatui
    repository: oci://ghcr.io/nceas/charts
    version: 1.0.7
    condition: global.includeMetacatUi

  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    # @param version  --  the bitnami postgresql CHART version, NOT the database version
    # get full list using:  $  helm search repo bitnami/postgresql --versions
    #
    version: 16.4.14    # chart version 16.4.14 deploys postgres version 17.4.0
    condition: postgresql.enabled

  - name: dataone-indexer
    repository: oci://ghcr.io/dataoneorg/charts
    version: 1.3.2
    condition: global.dataone-indexer.enabled
    import-values:
      - child: solr
        parent: dataone-indexer.solr
      - child: rabbitmq
        parent: dataone-indexer.rabbitmq
