apiVersion: v2
name: metacat
description: |
  Helm chart for Kubernetes Deployment of MetaCat 
  (https://github.com/NCEAS/metacat)

# OCI Annotations - see https://github.com/helm/helm/pull/11204
sources:
  - https://github.com/NCEAS/metacat

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.1-develop
icon: https://camo.githubusercontent.com/a41e704e6cbd198afed0a892f2dccfc43aef29fb7631407048f531aa31956e72/68747470733a2f2f6b6e622e65636f696e666f726d61746963732e6f72672f6b6e622f646f63732f5f696d616765732f6d6574616361742d6c6f676f2d6461726b677261792e706e67

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# NOTE that the chart will pull the docker image whose tag matches this value, if 'image.tag' is
# not set in values.yaml
appVersion: "3.0.0-no-mcui" ## metacat 3.0.0 code, but metacatui no longer bundled in docker image

# Chart dependencies - also see https://github.com/bitnami/charts/tree/main/bitnami
dependencies:
  - name: metacatui
    repository: oci://ghcr.io/nceas/charts
    version: 0.6.0
    ## NOT YET PUBLIC IN CHARTS REPO
    condition: global.includeMetacatUi

  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    # @param version  --  the bitnami postgresql CHART version, NOT the database version
    # get full list using:  $  helm search repo bitnami/postgresql --versions
    #
    version: 11.9.13    # postgres version 14.5.0 is deployed by chart version 11.9.13
    condition: postgresql.enabled

  - name: dataone-indexer
    repository: oci://ghcr.io/dataoneorg/charts
    version: 1.0.2-develop
    condition: global.dataone-indexer.enabled
    import-values:
      - child: solr
        parent: dataone-indexer.solr
      - child: rabbitmq
        parent: dataone-indexer.rabbitmq
