apiVersion: v2
name: metacat
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0
icon: https://camo.githubusercontent.com/a41e704e6cbd198afed0a892f2dccfc43aef29fb7631407048f531aa31956e72/68747470733a2f2f6b6e622e65636f696e666f726d61746963732e6f72672f6b6e622f646f63732f5f696d616765732f6d6574616361742d6c6f676f2d6461726b677261792e706e67

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.18.0"

# Chart dependencies
# dependencies:
#   - name: postgres
#     repository: https://charts.bitnami.com/bitnami
#     version: 14.6.0
#     condition: postgres.enabled, global.postgres.enabled
#   - name: solr
#     repository: https://charts.bitnami.com/bitnami
#     version: 6.2.3
#     condition: solr.enabled, global.solr.enabled
