DELETE FROM xml_index WHERE docid ='tao.12043';
DELETE FROM xml_access WHERE accessfileid ='tao.12043';
DELETE FROM xml_access WHERE docid ='tao.12043';
DELETE FROM xml_queryresult WHERE docid ='tao.12043';
DELETE FROM xml_relation WHERE docid ='tao.12043';
DELETE FROM xml_path_index WHERE docid ='tao.12043';
DELETE FROM xml_accesssubtree WHERE docid = 'tao.12043';
DELETE FROM xml_documents WHERE docid ='tao.12043';
DELETE FROM xml_nodes where docid ='tao.12043';

DELETE FROM xml_index WHERE docid ='tao.12045';
DELETE FROM xml_access WHERE accessfileid ='tao.12045';
DELETE FROM xml_access WHERE docid ='tao.12045';
DELETE FROM xml_queryresult WHERE docid ='tao.12045';
DELETE FROM xml_relation WHERE docid ='tao.12045';
DELETE FROM xml_path_index WHERE docid ='tao.12045';
DELETE FROM xml_accesssubtree WHERE docid = 'tao.12045';
DELETE FROM xml_documents WHERE docid ='tao.12045';
DELETE FROM xml_nodes where docid ='tao.12045';
